# Generated by Django 6.0.4 on 2026-05-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image_category_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_and_cleaning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='special_features',
            field=models.TextField(blank=True, default=''),
        ),
    ]
