# Generated by Django 6.0.4 on 2026-05-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/'),
        ),
    ]
