# Generated by Django 6.0.4 on 2026-05-20 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CategoryVariantTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_templates', to='products.category')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CategoryVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.categoryvarianttemplate')),
            ],
            options={
                'ordering': ['display_order', 'value'],
                'unique_together': {('template', 'value')},
            },
        ),
    ]
