# Generated by Django 6.0.4 on 2026-09-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvariant_attributes_categoryvarianttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('boys', "Boy's"), ('girls', "Girl's"), ('all', 'All')], default='boys', max_length=20),
        ),
    ]
