# Generated by Django 6.0.4 on 2026-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_display_count_category_gender'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured', 'id'], name='products_ca_is_feat_2ebe77_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['gender', 'is_featured'], name='products_ca_gender_daf5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='products_pr_is_acti_645007_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'slug'], name='products_pr_is_acti_0bb38e_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'order'], name='products_pr_product_e55bb9_idx'),
        ),
    ]
