# Generated by Django 6.0.4 on 2026-09-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_products_ca_is_feat_2ebe77_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_banners/'),
        ),
    ]
