# Generated by Django 6.0.4 on 2026-09-26 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_sizechart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('outfit', 'Outfit'), ('related', 'Related'), ('complementary', 'Complementary')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='products.product')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['source', 'intent', 'order'], name='products_pr_source__1af030_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'intent', 'target'), name='unique_product_link'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='product_link_no_self')],
            },
        ),
    ]
