# Generated by Django 6.0.4 on 2026-09-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_material_source_product_material_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
