from django.urls import path
from .media_rights_views import AdminMediaRightsView
from .page_views import OwnerPageListView, OwnerPageDetailView
from .catalog_content_views import (
    AdminProductLinksView, AdminLookbookHotspotsView,
    AdminEditorialListView, AdminEditorialDetailView, AdminEditorialSchemaView, AdminNewsletterSubscribersView,
)
from .views import (
    DashboardView, AdminOrderListView, AdminOrderDetailView,
    AdminProductImageView, AdminProductDetailView, AdminProductListView,
    AdminCategoryListView, AdminCategoryDetailView,
    AdminBannerListView, AdminBannerDetailView,
    AdminMonthlySummaryView,
    AdminReviewListView, AdminReviewDetailView,
    AdminCustomerListView, AdminCustomerDetailView,
    AdminCouponListView, AdminCouponDetailView,
    AdminSettingsView,
    AdminInventoryView, AdminInventoryVariantView,
    AdminProductVariantListView,
    AdminProductVariantDetailView,
    AdminMegaMenuSectionListView,
    AdminMegaMenuSectionDetailView,
    AdminMegaMenuSectionCategoriesView,
    AdminMegaMenuSectionCategoryImageView,
    AdminCollectionsMenuColumnListView,
    AdminCollectionsMenuColumnDetailView,
    AdminCollectionsMenuLinkListView,
    AdminCollectionsMenuLinkDetailView,
    AdminCollectionsMenuPromoListView,
    AdminCollectionsMenuPromoDetailView,
    AdminShopMenuPromoListView,
    AdminShopMenuPromoDetailView,
    AdminCategoryVariantTemplateListView,        
    AdminCategoryVariantTemplateDetailView,      
    AdminCategoryVariantOptionListView,           
    AdminCategoryVariantOptionDetailView,         
    AdminCollectionListView,
    AdminCollectionDetailView,
    AdminCollectionRulesView,
    AdminCollectionProductsView,
    AdminCollectionPreviewView,
    AdminTagListView,
    AdminTagDetailView,
)

urlpatterns = [
    path('media-rights/', AdminMediaRightsView.as_view()),
    path('pages/', OwnerPageListView.as_view()),
    path('pages/<int:pk>/', OwnerPageDetailView.as_view()),
    path('home/newsletter-subscribers/', AdminNewsletterSubscribersView.as_view()),
    path('products/<int:pk>/links/<str:intent>/', AdminProductLinksView.as_view()),
    path('home/lookbooks/<int:pk>/hotspots/', AdminLookbookHotspotsView.as_view()),
    path('home/content/<str:kind>/schema/', AdminEditorialSchemaView.as_view()),
    path('home/content/<str:kind>/', AdminEditorialListView.as_view()),
    path('home/content/<str:kind>/<int:pk>/', AdminEditorialDetailView.as_view()),
    path('dashboard/', DashboardView.as_view()),
    path('orders/', AdminOrderListView.as_view()),
    path('orders/<int:pk>/', AdminOrderDetailView.as_view()),
    path('orders/monthly-summary/', AdminMonthlySummaryView.as_view()),
    path('products/', AdminProductListView.as_view()),
    path('products/<int:pk>/', AdminProductDetailView.as_view()),
    path('products/<int:pk>/images/', AdminProductImageView.as_view()),
    path('products/<int:pk>/images/<int:image_id>/', AdminProductImageView.as_view()),
    path('products/<int:pk>/variants/', AdminProductVariantListView.as_view()),
    path('products/<int:pk>/variants/<int:variant_pk>/', AdminProductVariantDetailView.as_view()),
    path('categories/', AdminCategoryListView.as_view()),
    path('categories/<int:pk>/', AdminCategoryDetailView.as_view()),
    path('tags/', AdminTagListView.as_view()),
    path('tags/<int:pk>/', AdminTagDetailView.as_view()),
    path('banners/', AdminBannerListView.as_view()),
    path('banners/<int:pk>/', AdminBannerDetailView.as_view()),
    path('mega-menu-sections/', AdminMegaMenuSectionListView.as_view()),
    path('mega-menu-sections/<int:pk>/', AdminMegaMenuSectionDetailView.as_view()),
    path(
        'mega-menu-sections/<int:pk>/categories/',
        AdminMegaMenuSectionCategoriesView.as_view(),
    ),
    path('mega-menu-sections/<int:pk>/categories/<int:category_id>/image/',
         AdminMegaMenuSectionCategoryImageView.as_view()),
    path('reviews/', AdminReviewListView.as_view()),
    path('reviews/<int:pk>/', AdminReviewDetailView.as_view()),
    path('customers/', AdminCustomerListView.as_view()),
    path('customers/<int:pk>/', AdminCustomerDetailView.as_view()),
    path('coupons/', AdminCouponListView.as_view()),
    path('coupons/<int:pk>/', AdminCouponDetailView.as_view()),
    path('settings/', AdminSettingsView.as_view()),
    path('inventory/', AdminInventoryView.as_view()),
    path('inventory/variants/<int:pk>/', AdminInventoryVariantView.as_view()),
    path('collections-menu/columns/', AdminCollectionsMenuColumnListView.as_view()),
    path('collections-menu/columns/<int:pk>/', AdminCollectionsMenuColumnDetailView.as_view()),
    path('collections-menu/columns/<int:column_id>/links/', AdminCollectionsMenuLinkListView.as_view()),
    path('collections-menu/links/<int:pk>/', AdminCollectionsMenuLinkDetailView.as_view()),
    path('collections-menu/promos/', AdminCollectionsMenuPromoListView.as_view()),
    path('collections-menu/promos/<int:pk>/', AdminCollectionsMenuPromoDetailView.as_view()),
    path('shop-menu/promos/', AdminShopMenuPromoListView.as_view()),
    path('shop-menu/promos/<int:pk>/', AdminShopMenuPromoDetailView.as_view()),
    path('categories/<int:category_id>/variant-templates/', AdminCategoryVariantTemplateListView.as_view()),
    path('categories/<int:category_id>/variant-templates/<int:pk>/', AdminCategoryVariantTemplateDetailView.as_view()),
    path('categories/<int:category_id>/variant-templates/<int:template_pk>/options/', AdminCategoryVariantOptionListView.as_view()),
    path('categories/<int:category_id>/variant-templates/<int:template_pk>/options/<int:pk>/', AdminCategoryVariantOptionDetailView.as_view()),
    path('collections/', AdminCollectionListView.as_view()),
    path('collections/preview/', AdminCollectionPreviewView.as_view()),
    path('collections/<int:pk>/', AdminCollectionDetailView.as_view()),
    path('collections/<int:pk>/rules/', AdminCollectionRulesView.as_view()),
    path('collections/<int:pk>/products/', AdminCollectionProductsView.as_view()),
]
