# Generated by Django 6.0.4 on 2026-09-26 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_tag_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('collection_type', models.CharField(choices=[('smart', 'Smart (rule-based)'), ('manual', 'Manual (hand-picked)')], default='smart', max_length=10)),
                ('match_mode', models.CharField(choices=[('all', 'Match all rules (AND)'), ('any', 'Match any rule (OR)')], default='all', max_length=3)),
                ('sort', models.CharField(choices=[('newest', 'Newest'), ('best_selling', 'Best selling'), ('price_asc', 'Price: low to high'), ('price_desc', 'Price: high to low'), ('top_rated', 'Top rated'), ('manual', 'Manual order')], default='newest', max_length=20)),
                ('limit', models.PositiveIntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'slug'], name='collections_is_acti_b16173_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmartCollectionHide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hides', to='collections.smartcollection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('collection', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SmartCollectionManualProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_products', to='collections.smartcollection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('collection', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SmartCollectionPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='collections.smartcollection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('collection', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SmartCollectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('field', models.CharField(choices=[('created_at', 'Created date'), ('price', 'Price'), ('category', 'Category'), ('gender', 'Gender'), ('in_stock', 'In stock'), ('on_sale', 'On sale'), ('badge', 'Badge'), ('tag', 'Tag'), ('rating', 'Rating')], max_length=30)),
                ('operator', models.CharField(choices=[('eq', 'equals'), ('neq', 'not equals'), ('gt', 'greater than'), ('gte', 'greater than or equal'), ('lt', 'less than'), ('lte', 'less than or equal'), ('in', 'is one of'), ('within_days', 'within last N days')], default='eq', max_length=20)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='collections.smartcollection')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['collection', 'order'], name='collections_collect_385d88_idx')],
            },
        ),
    ]
