# Generated by Django 6.0.4 on 2026-09-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartcollection',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='smartcollection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='smartcollection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
        migrations.AddField(
            model_name='smartcollection',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartcollection',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
