# Generated by Django 6.0.4 on 2026-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='My Store', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('promo_bar_text', models.CharField(blank=True, default='', max_length=300)),
                ('promo_bar_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
