# Generated by Django 6.0.4 on 2026-05-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_add_store_settings'),
        ('products', '0006_product_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('new_arrivals', 'New Arrivals'), ('best_sellers', 'Best Sellers'), ('clothing', 'Clothing'), ('shop_all', 'Shop All')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('use_manual_categories', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MegaMenuSectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='home.megamenusection')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('section', 'category')},
            },
        ),
    ]
