# Generated by Django 6.0.4 on 2026-09-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_collectionsmenucolumn_collectionsmenupromo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslide',
            name='bg_color',
            field=models.CharField(blank=True, default='#C99484', max_length=30),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_transition',
            field=models.CharField(choices=[('fade_zoom', 'Fade & Gentle Zoom (Ken Burns)'), ('slide', 'Horizontal Slide')], default='fade_zoom', max_length=30),
        ),
    ]
