# Generated by Django 6.0.4 on 2026-09-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bannerslide_bg_color_storesettings_hero_transition'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewInShowcaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lifestyle_image', models.ImageField(upload_to='showcase_images/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='showcase_images/')),
                ('product_link', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
