# Generated by Django 6.0.4 on 2026-09-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newinshowcasecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitHighlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subheading', models.CharField(max_length=150)),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_image', models.ImageField(upload_to='highlight_images/')),
                ('lifestyle_image', models.ImageField(upload_to='highlight_images/')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
