# Generated by Django 6.0.4 on 2026-09-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_outfithighlightitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayeredScrollingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('subheading', models.CharField(max_length=150)),
                ('heading', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='layered_cards/')),
                ('button_text', models.CharField(default='Shop now', max_length=50)),
                ('link_url', models.CharField(default='/collections/all', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
