# Generated by Django 6.0.4 on 2026-09-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_layeredscrollingcard'),
        ('products', '0008_category_display_count_category_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookbookCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='lookbook_cards/')),
                ('item_count_label', models.CharField(default='2 items', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tagged_products', models.ManyToManyField(blank=True, related_name='lookbook_cards', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
