# Generated by Django 6.0.4 on 2026-09-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_lookbookcard'),
        ('products', '0008_category_display_count_category_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsHighlightSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='HOT ITEMS', max_length=100)),
                ('heading', models.CharField(default='Shop The Winter\nSet', max_length=255)),
                ('description', models.TextField(default='Comfortably wear Oura Ring all day and night to collect deeply personal health metrics.')),
                ('button_text', models.CharField(default='Shop now', max_length=50)),
                ('button_link', models.CharField(default='/products/denim-jeans-kids', max_length=255)),
                ('banner_image', models.ImageField(upload_to='highlight_banners/')),
                ('video_url', models.CharField(blank=True, max_length=500)),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='highlight_posters/')),
                ('is_active', models.BooleanField(default=True)),
                ('carousel_products', models.ManyToManyField(blank=True, related_name='highlight_sections', to='products.product')),
            ],
        ),
    ]
