# Generated by Django 6.0.4 on 2026-09-18 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_productshighlightsection'),
        ('products', '0008_category_display_count_category_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSuggestionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='How you style it', max_length=100)),
                ('heading', models.TextField(default='Dress up in 3 steps.\nPick - Pair - Play!')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSuggestionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('badge_1', models.CharField(blank=True, max_length=100)),
                ('badge_2', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, related_name='suggestion_steps', to='products.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='home.productsuggestionsection')),
            ],
            options={
                'ordering': ['order', 'step_number'],
            },
        ),
    ]
