# Generated by Django 6.0.4 on 2026-09-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_productsuggestionsection_productsuggestionstep'),
        ('products', '0008_category_display_count_category_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsBundleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Bundle & Save', max_length=100)),
                ('heading', models.CharField(default='Buy 2 Get 10% Off', max_length=255)),
                ('discount_percentage', models.PositiveIntegerField(default=10)),
                ('banner_image', models.ImageField(upload_to='bundle_banners/')),
                ('hotspot_1_x', models.FloatField(default=56.0)),
                ('hotspot_1_y', models.FloatField(default=26.0)),
                ('hotspot_2_x', models.FloatField(default=40.0)),
                ('hotspot_2_y', models.FloatField(default=62.0)),
                ('button_text', models.CharField(default='Add all to cart', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('bundle_products', models.ManyToManyField(blank=True, related_name='bundle_sections', to='products.product')),
            ],
        ),
    ]
