# Generated by Django 6.0.4 on 2026-09-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_productsbundlesection'),
        ('products', '0008_category_display_count_category_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsParallaxSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='What customers say', max_length=100)),
                ('heading', models.CharField(default='Over 500\nHappy Reviews', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('image', models.ImageField(upload_to='testimonial_images/')),
                ('column_index', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='products.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='home.testimonialsparallaxsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
