# Generated by Django 6.0.4 on 2026-09-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_testimonialsparallaxsection_testimonialitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPillarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='brand_pillars/')),
                ('button_text', models.CharField(default='shop', max_length=50)),
                ('button_link', models.CharField(default='/collections/all', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OurStorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='our story', max_length=100)),
                ('heading', models.CharField(default='Delicate ruffles with soft finishes.', max_length=255)),
                ('description', models.TextField(default='Designed with movement in mind, our pieces offer breathable comfort and relaxed silhouettes. Subtle details add personality without compromising ease. Carefully crafted details bring a playful touch while staying soft against the skin.')),
                ('button_text', models.CharField(default='Learn more', max_length=50)),
                ('button_link', models.CharField(default='/pages/our-journal', max_length=255)),
                ('image', models.ImageField(upload_to='story_images/')),
                ('badge_1_text', models.CharField(default='Wow', max_length=50)),
                ('badge_1_color', models.CharField(default='#BDE6EE', max_length=30)),
                ('badge_2_text', models.CharField(default='Playful', max_length=50)),
                ('badge_2_color', models.CharField(default='#FFC8C8', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
