# Generated by Django 6.0.4 on 2026-09-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_brandpillaritem_ourstorysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexCarouselSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Dress your explorer in comfort', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlexCarouselCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('heading', models.CharField(max_length=255)),
                ('subtext', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='flex_carousel_cards/')),
                ('width_desktop_percent', models.PositiveSmallIntegerField(default=30)),
                ('link', models.CharField(default='/collections/all', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='home.flexcarouselsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
