# Generated by Django 6.0.4 on 2026-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_flexcarouselsection_flexcarouselcard'),
        ('products', '0009_category_products_ca_is_feat_2ebe77_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bannerslide',
            index=models.Index(fields=['is_active', 'order'], name='home_banner_is_acti_c004cf_idx'),
        ),
        migrations.AddIndex(
            model_name='brandpillaritem',
            index=models.Index(fields=['is_active', 'order'], name='home_brandp_is_acti_4c688f_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionsmenucolumn',
            index=models.Index(fields=['is_active', 'order'], name='home_collec_is_acti_bc3700_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionsmenulink',
            index=models.Index(fields=['column', 'order'], name='home_collec_column__c73126_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionsmenulink',
            index=models.Index(fields=['is_active', 'order'], name='home_collec_is_acti_07251a_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionsmenupromo',
            index=models.Index(fields=['is_active', 'order'], name='home_collec_is_acti_37906a_idx'),
        ),
        migrations.AddIndex(
            model_name='flexcarouselcard',
            index=models.Index(fields=['section', 'order'], name='home_flexca_section_88f2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='flexcarouselcard',
            index=models.Index(fields=['is_active', 'order'], name='home_flexca_is_acti_42b9d8_idx'),
        ),
        migrations.AddIndex(
            model_name='layeredscrollingcard',
            index=models.Index(fields=['is_active', 'order'], name='home_layere_is_acti_a808a9_idx'),
        ),
        migrations.AddIndex(
            model_name='lookbookcard',
            index=models.Index(fields=['is_active', 'order'], name='home_lookbo_is_acti_50a46f_idx'),
        ),
        migrations.AddIndex(
            model_name='newinshowcasecard',
            index=models.Index(fields=['is_active', 'order'], name='home_newins_is_acti_0c25f7_idx'),
        ),
        migrations.AddIndex(
            model_name='outfithighlightitem',
            index=models.Index(fields=['is_active', 'order'], name='home_outfit_is_acti_ffc639_idx'),
        ),
        migrations.AddIndex(
            model_name='productsuggestionstep',
            index=models.Index(fields=['section', 'order'], name='home_produc_section_0b4d14_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonialitem',
            index=models.Index(fields=['section', 'order'], name='home_testim_section_376dd0_idx'),
        ),
    ]
