# Generated by Django 6.0.4 on 2026-09-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_bannerslide_home_banner_is_acti_c004cf_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('route', models.CharField(default='/collections', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PagesMenuCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='pages_menu/')),
                ('route', models.CharField(default='/pages/our-story', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PagesMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PagesMenuSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_we_are_title', models.CharField(default='Who We Are', max_length=150)),
                ('who_we_are_text', models.TextField(default='We create simple, well-made essentials that balance comfort and style, giving kids the freedom to explore, play, and grow every day.')),
            ],
        ),
        migrations.CreateModel(
            name='ShopMenuPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='NEW COLLECTION', max_length=100)),
                ('title', models.CharField(default='The Cozy Crew', max_length=200)),
                ('cta_text', models.CharField(default='Shop Now', max_length=80)),
                ('cta_link', models.CharField(default='/products', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_promos/')),
                ('bg_color', models.CharField(default='#84A999', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesMenuSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('route', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='home.featuresmenuitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
