# Generated by Django 6.0.4 on 2026-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_featuresmenuitem_pagesmenucard_pagesmenulink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopmenupromo',
            options={'verbose_name': 'Shop Menu Promo', 'verbose_name_plural': 'Shop Menu Promos'},
        ),
        migrations.AddField(
            model_name='shopmenupromo',
            name='section',
            field=models.CharField(choices=[('new_arrivals', 'New Arrivals'), ('best_sellers', 'Best Sellers'), ('clothing', 'Clothing'), ('shop_all', 'Shop All')], default='new_arrivals', help_text='Header Shop menu section to which this promo belongs', max_length=50, unique=True),
        ),
    ]
