# Generated by Django 6.0.4 on 2026-09-26 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        ('home', '0018_alter_shopmenupromo_options_shopmenupromo_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='megamenusection',
            name='display_mode',
            field=models.CharField(choices=[('categories', 'Categories'), ('products', 'Products')], default='categories', max_length=12),
        ),
        migrations.AddField(
            model_name='megamenusection',
            name='smart_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mega_menu_sections', to='collections.smartcollection'),
        ),
    ]
