# Generated by Django 6.0.4 on 2026-09-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_seed_header_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustbadge',
            name='icon_key',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('returns', 'Returns'), ('payment', 'Payment'), ('service', 'Service')], max_length=60),
        ),
    ]
