# Generated by Django 6.0.4 on 2026-09-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_trustbadge_icon_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsuggestionstep',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonialitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
