# Generated by Django 6.0.4 on 2026-09-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_productsuggestionstep_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInstagramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='footer_instagram/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='footersettings',
            name='instagram_handle',
            field=models.CharField(default='@littlepebble.co', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='instagram_heading',
            field=models.CharField(default='Follow Us on Instagram', max_length=120),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='pinterest_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='x_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='column',
            field=models.CharField(choices=[('company', 'Company'), ('collection', 'Collection'), ('help', 'Get Help'), ('legal', 'Legal')], max_length=50),
        ),
    ]
