# Generated by Django 6.0.4 on 2026-09-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_mediarightsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='megamenusectioncategory',
            name='image_override',
            field=models.ImageField(blank=True, null=True, upload_to='menu_category_images/'),
        ),
    ]
