# Generated by Django 6.0.4 on 2026-09-28 07:11

import django.db.models.deletion
from django.db import migrations, models


def seed_new_in_button(apps, schema_editor):
    Settings = apps.get_model('home', 'NewInShowcaseSettings')
    Collection = apps.get_model('collections', 'SmartCollection')
    outerwear = Collection.objects.filter(slug='outerwear').first()
    Settings.objects.get_or_create(
        pk=1,
        defaults={
            'button_text': 'Shop Now',
            'cta_link': '/collections/outerwear',
            'destination_collection_id': outerwear.pk if outerwear else None,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_fill_clothing_collection'),
        ('home', '0037_align_shop_menu_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewInShowcaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('cta_link', models.CharField(default='/collections/outerwear', editable=False, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('destination_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collections.smartcollection')),
            ],
        ),
        migrations.RunPython(seed_new_in_button, migrations.RunPython.noop),
    ]
