# Generated by Django 6.0.4 on 2026-04-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='newslatter_opt_in',
            new_name='newsletter_opt_in',
        ),
    ]
