# Generated by Django 6.0.4 on 2026-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_newslatter_opt_in_userprofile_newsletter_opt_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
