# Generated by Django 6.0.4 on 2026-09-29 07:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_status_history(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Event = apps.get_model('orders', 'OrderStatusEvent')
    db = schema_editor.connection.alias
    events = []
    for order in Order.objects.using(db).all().iterator():
        events.append(Event(order_id=order.id, status='pending', occurred_at=order.created_at))
        if order.status in ('shipped', 'delivered') and order.shipped_at:
            events.append(Event(order_id=order.id, status='shipped', occurred_at=order.shipped_at))
        if order.status != 'pending' and not (order.status == 'shipped' and order.shipped_at):
            events.append(Event(order_id=order.id, status=order.status, occurred_at=order.updated_at))
    Event.objects.using(db).bulk_create(events, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_backfill_pricing_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='orders.order')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['order', 'occurred_at'], name='orders_orde_order_i_8d517b_idx')],
            },
        ),
        migrations.RunPython(backfill_status_history, migrations.RunPython.noop),
    ]
