# Generated by Django 6.0.4 on 2026-09-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderstatusevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
